# Generated by Django 6.0.2 on 2026-03-17 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='session_id',
            field=models.CharField(default='default', max_length=100),
        ),
    ]
